### ISSUE TITLE
[2.0.1] composes broken ?

### ISSUE THREAD

**Issue by joscha** [css-modules/postcss-icss-values#107]
After updating from `postcss-modules-values@1.3.0` to `postcss-icss-values@2.0.1` I get the following errors in my CSS build:

```
./src/ui/badge/stories/badge.stories.css
Module build failed: ModuleBuildError: Module build failed: referenced class name "__value__heavyBoxShadow__2" in composes not found (19:4)
 
  17 | }
  18 |
> 19 | [dir=rtl] :export {
     |    ^
  20 |   heavyBoxShadow: __value__heavyBoxShadow__-2;
  21 | }
  22 |
```
The CSS files look like this:

`ui/shadows/shadows.cs`:
```css
@value monoBlackA275 from "../colors/colors.css";
@value monoBlackA500 from "../colors/colors.css";

.heavyBoxShadow {
    box-shadow: 0 0 0 1px monoBlackA500, 0 2px 18px monoBlackA275;
}
```

and the one using it, `badge.stories.css`:
```css
@value heavyBoxShadow from "ui/shadows/shadows.css";

.shadow {
    composes: heavyBoxShadow;
}
```

any idea what could have caused this in the upgrade?
