### ISSUE TITLE
Using imported value in rgba()

### ISSUE THREAD

**Issue by jerrysu** [css-modules/postcss-icss-values#17]
I have the following:

```
/* colors.css */
@value midnight: #182947;
```

```
/* foo.css */
@value midnight from './colors.css';

.root {
  background-color: midnight;
  background-color: rgba(midnight, 0.97);
}
```

The output of this that I see in the browser is (similar to):

```
.foo__root___hwRbh {
  background-color: #182947;
  background-color: rgba(i__const_midnight_0, 0.97);
}
```

The value for `midnight` is not being interpolated correctly in the rgba() instance.

This occurs with `css-loader@1.1.0` and with `postcss-loader` removed from my webpack configuration (I thought maybe one of my postcss plugins were conflicting).

Is this a bug? Or an unsupported use case?

**Comment by jgrancher** [comment]
+1 for this. I've got the same issue... :(

**Comment by jamesmccann-zz** [comment]
Having a similar issue using `calc`.

With https://github.com/css-modules/postcss-modules-values/commit/e8345f9d20f335bfc48cdc93009b9dd6c5c6543f it works for me with a locally defined value but not a value imported from another file, i.e.:

``` css
// works
@value navbarHeight: 50px;

// doesn't work
@value navbarHeight from 'shared/styles/constants.css';

.panel {
  width: 350px;
  height: calc(100vh - navbarHeight);
}
```
