### ISSUE TITLE
Transitive values

### ISSUE THREAD

**Issue by sokra** [css-modules/postcss-icss-values#2]
``` css
@value aaa: red;
@value bbb: aaa;

.a { color: bbb; }
```

should be `.a { color: red; }`

**Comment by ctaepper** [comment]
even better use case:

```
@value margin-base: 20px;
@value margin-large: margin-base * 2;
```

**Comment by geelen** [comment]
@ctaepper nice idea, but I think that example needs to be:

``` css
@value margin-base: 20px;
@value margin-large: calc(margin-base * 2);

.a { margin: margin-base; }
.b { margin: margin-large; }
```

I don't think this plugin should be doing anything except simple substitution, so the resulting output would be:

``` css
.a { margin: 20px; }
.b { margin: calc(20px * 2); }
```

You'd then be able to run this through [postcss-calc](https://github.com/postcss/postcss-calc) to compile any `calc` expressions down to their result if you wanted. I personally wouldn't bother, except maybe as a minification step for production use.

**Comment by ctaepper** [comment]
@geelen yes you are right. i initially tried it that way, only ending up with something like this in the output css

``` css
.b { margin: calc(i_const_a342 * 2); }
```

i am trying css modules for a smaller project switching from Harry Roberts' inuitcss framework and this is a function i am really missing here.
