### ISSUE TITLE
Using module reference in composes

### ISSUE THREAD

**Issue by tabazevedo** [css-modules/postcss-icss-values#26]
The following doesn't seem to work:

``` css
@value typography: "../styles/typography.css";

.headline {
  composes: serif from typography;
  display: block;
}
```

However, importing the values explicitly does work:

``` css
@value typography: "../styles/typography.css";
@value serif from typography;

.headline {
  composes: serif;
  display: block;
}
```

The first makes webpack explode with `referenced class name "serif" in composes not found`.
Am I missing something? I thought the first was valid syntax, and is demonstrated in this repo's readme.

My webpack config:

``` js
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

var postcssPlugins = [
  "postcss-cssnext",
  "autoprefixer",
  "postcss-discard-duplicates"
].map(require);

var plugins = [
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development')
    }
  }),
  new ExtractTextPlugin('main.css'),
  new webpack.NoErrorsPlugin(),
  new webpack.optimize.DedupePlugin()
];

if(process.env.NODE_ENV === 'production') {
  plugins.push(new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false
    }
  }));
}

var config = {
  entry: './src/client.js',
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'main.js'
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json' },
      { test: /\.js$/, loader: 'babel', exclude: /node_modules/ },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract([
          'css-loader?' + [
            'modules',
            // 'minimize',
            'importLoaders=1',
            'localIdentName=[name]__[local]_[hash:base64]'
          ].join('&'),
          'postcss-loader'
        ].join('!'))
      }
    ]
  },
  resolveLoader: {
    fallback:  path.join(__dirname, 'node_modules')
  },
  postcss: () => postcssPlugins,
  plugins: plugins,
  devtool: 'source-map'
};

module.exports = config;
```
