### ISSUE TITLE
Multi-line @value imports?

### ISSUE THREAD

**Issue by jerrysu** [css-modules/postcss-icss-values#41]
Is there any way to have multi-line declarations when importing with `@value`?

I often have something like:

```
@value small as spacing-small, medium as spacing-medium, large as spacing-large from 'spacing.css';
```

I would like to express this as:

```
@value (
  small as spacing-small,
  medium as spacing-medium,
  large as spacing-large,
) from 'spacing.css';
```

Or something similar.

For the time-being, I've opted to just do one import per declaration, like so:

```
@value small as spacing-small from 'spacing.css';
@value medium as spacing-medium from 'spacing.css';
@value large as spacing-large from 'spacing.css';
```

Thoughts?

**Comment by geelen** [comment]
I like this a lot. I had this exact problem the other day, where I was making aliases for colours. With your syntax, that would look something like this:

``` css
@value (
  bright-blue as section-dashboard,
  orange as section-reports,
  red as section-settings
) from 'traits/colours.css';

.dashboard {
  border-left-color: section-dashboard;
}
.reports {
  border-left-color: section-reports;
}
.settings {
  border-left-color: section-settings;
}
```

Checking http://www.sassmeister.com/ and https://sneakertack.github.io/postcss-playground/ that syntax seems to pass through both parsers ok, so I think this could work. Not sure when I'll get a chance to implement though, but will close this issue when it's done.

Thanks!
