### ISSUE TITLE
Negative value doesn't work

### ISSUE THREAD

**Issue by octopitus** [css-modules/postcss-icss-values#51]
``` css
@value sidebarWidth: 240px;

.sidebar {
   transform: translateX(-sidebarWidth)
}
```

Result (`sidebarWidth` isn't being transformed):

``` css
.sidebar {
   transform: translateX(-sidebarWidth)
}
```

Any ideas?
