### ISSUE TITLE
Comma-Separated Values

### ISSUE THREAD

**Issue by alexlafroscia** [css-modules/postcss-icss-values#74]
I'm seeing problems when trying to use an `@value` with a `font-family` definition.  For example:

``` css
@value my-font-fam: 'Some-Custom-Font', Helvetica;

.foo {
  font-family: my-font-fam;
}
```

Results in:

``` css
.foo {
  font-family: 'Some-Custom-Font';
}
```

A longer `@value` definition, such as

``` css
@value my-font-fam: 'Some-Custom-Font', Helvetica, Arial, 'Lucida Granda', sans-serif;
```

results in the same output.

Possibly related to #68 (issues with comma-separated media queries) but I'm not sure.

**Comment by alexlafroscia** [comment]
I see that there's a [test here](https://github.com/css-modules/postcss-modules-values/blob/10974bc184ee3775d0c1a60df59eb6bec899c7de/test/index.js#L144-L150) verifying that they _should_ be supported... I'm not sure why I'm running into problems here.

**Comment by mndewitt** [comment]
Appears to be an issue with the single quotes - I've been able use commas in media queries.

**Comment by OliverJAsh** [comment]
I've also just been hit by this. Is there any known work around?

**Comment by TrySound** [comment]
Well, guys. I can't reproduce this issue. Can you help with debugging?

**Comment by OliverJAsh** [comment]
My example is almost identical to the original post: using `@value` to store the font family value, which contains commas.

``` css
@value fontFamilyValue: foo, bar, baz

body {
  font-family: fontFamilyValue;
}
```

Result is:

``` css
body {
  font-family: foo;
}
```

I am reproducing this when using CSS Modules via [`css-loader`’s `modules` option](https://github.com/webpack-contrib/css-loader#options), if that has anything to do with it.
