### ISSUE TITLE
README is misleading: cannot compose from value

### ISSUE THREAD

**Issue by OliverJAsh** [css-modules/postcss-icss-values#98]
The README suggests you can import a file and then use the identifier in a `composes` value, e,g,:

``` css
@value foo: "./foo.css";
.bar {
  composes: baz from foo;
}
```

However, this errors with:

```
referenced class name "from" in composes not found
```
